# Generated by Django 3.2.6 on 2023-01-13 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inviteduser',
            name='user_role',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
