# Generated by Django 3.2.6 on 2023-01-13 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_inviteduser_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inviteduser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
