# Generated by Django 3.2.6 on 2023-01-14 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_supplier_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='Email',
            new_name='email',
        ),
    ]
