# Generated by Django 3.2.6 on 2023-01-15 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_email_supplier_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inviteduser',
            name='user_role',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_role',
        ),
    ]
